// Sources: Google Scholar (user=hKmk0z4AAAAJ), ORCID 0000-0002-9171-6922. Retrieved 29 Sep 2026.
// Duplicates, corrections and preprints superseded by a journal version are removed.
window.SITE = {
  stats: { citations: 488, hIndex: 12, i10: 14, asOf: "September 2026" },
  links: {
    email: "yamina.boukari@jesus.ox.ac.uk",
    scholar: "https://scholar.google.com/citations?user=hKmk0z4AAAAJ&hl=en",
    orcid: "https://orcid.org/0000-0002-9171-6922",
    linkedin: "https://www.linkedin.com/in/yaminaboukari/",
    researchgate: "https://www.researchgate.net/profile/Yamina-Boukari",
    bennett: "https://www.bennett.ox.ac.uk/about-us/yamina-boukari/",
    jesus: "https://www.jesus.ox.ac.uk/about-jesus-college/our-community/people/dr-yamina-boukari/"
  },
  themes: {
    data: "Migration & health data",
    covid: "COVID-19 & migrants",
    justice: "Racism, conflict & policy",
    biomat: "Biomaterials (PhD)"
  },
  pubs: [
    { y: 2026, t: "The health impacts of illegal pushbacks at European borders on children", a: "A Stevens, Y Boukari, S English, L Gram, L Kiss, J Mannell, V Radaiou, et al.", v: "Population Medicine 8(1)", type: "Abstract", theme: "justice", c: 0 },
    { y: 2026, t: "Challenging the bystander effect: towards a socially-just global health academic culture", a: "O Bouaddi, F Seedat, Y Boukari, A Deivanayagam", v: "Population Medicine 8(1)", type: "Abstract", theme: "justice", c: 0 },
    { y: 2026, t: "The impact of Islamophobia on migrants' health and wellbeing outcomes: a systematic literature review", a: "Y Boukari, G Cronin, U Beg, H Shahid, S Shoeb, G Samari, F Seedat, et al.", v: "Population Medicine 8(1)", type: "Abstract", theme: "justice", c: 0 },
    { y: 2026, t: "Determining the migration status of 24 million individuals living in England using the OpenSAFELY platform", a: "Y Boukari, M Pesce, J Scuffell, N Aspray, B Goldacre, W Hulme", v: "Population Medicine 8(1)", type: "Abstract", theme: "data", c: 0 },
    { y: 2026, t: "Pre-pregnancy primary care and accident and emergency interactions among interpreter-users versus non-interpreter-users in England: a retrospective cohort study", a: "M McGranahan, NS Clemente, L Murdock, B Njie, Y Boukari, Z Welshman, et al.", v: "BMJ Public Health 4(3)", type: "Article", theme: "data", c: 0, doi: "10.1136/bmjph-2025-003450" },
    { y: 2026, t: "The UCL–Lancet Commission on Migration and Health: review of the state of progress", a: "I Abubakar, D Tellez, RW Aldridge, C Altare, ML Barreto, Y Boukari, et al.", v: "The Lancet 407(10547), 2554–2576", type: "Article", theme: "justice", c: 1, doi: "10.1016/s0140-6736(26)00494-0", featured: true },
    { y: 2026, t: "Exploring the coding of migration status in English primary care from 2011 to 2025 using OpenCodeCounts", a: "Y Boukari, L Hiam, J Scuffell, A Tamborska, R Burns, M Wiedemann, et al.", v: "BJGP Open", type: "Article", theme: "data", c: 1, doi: "10.3399/BJGPO.2025.0138", featured: true },
    { y: 2025, t: "UK asylum proposals harm health and human rights", a: "Y Boukari, AJ Stevens, S Corona, D Devakumar", v: "BMJ 391", type: "Commentary", theme: "justice", c: 1 },
    { y: 2025, t: "Time to act: addressing discriminatory, racist and xenophobic health system policies and practice against forcibly displaced children in Europe", a: "A Stevens, Y Boukari, S English, A Kadir, B Kumar, D Devakumar", v: "European Journal of Public Health 35(Suppl 6)", type: "Abstract", theme: "justice", c: 0 },
    { y: 2025, t: "OpenCodeCounts: an open-access, interactive online tool and R package for analysing clinical code usage in England", a: "AA Tamborska, R Higgins, Y Boukari, V Kingsley, L Ojedele, K Oreagba, et al.", v: "medRxiv", type: "Preprint", theme: "data", c: 2, doi: "10.1101/2025.10.14.25338005" },
    { y: 2025, t: "Planned and emergency hospital admissions of 1.2 million adult non-EU migrants and refugees in England", a: "R Burns, S Wyke, Y Boukari, MT Eyre, V Nguyen, N Pathak, KM Lewis, et al.", v: "International Journal of Population Data Science 10(4)", type: "Abstract", theme: "data", c: 0 },
    { y: 2025, t: "The coding of migration status in English General Practice data from 2011 to 2024", a: "Y Boukari, L Hiam, J Scuffell, R Burns, A Tamborska, M Wiedemann", v: "International Journal of Population Data Science 10(4)", type: "Abstract", theme: "data", c: 0 },
    { y: 2025, t: "UK Longitudinal Linkage Collaboration (UK LLC): the national trusted research environment for longitudinal research", a: "A Boyd, KM Evans, EL Turner, R Flaig, J Oakley, KC Campbell, R Thomas, et al.", v: "International Journal of Population Data Science 10(1), 2468", type: "Article", theme: "data", c: 16 },
    { y: 2024, t: "Far-right riots in the UK: the culmination of years of rhetoric and policies", a: "Y Boukari, D Devakumar", v: "The Lancet 404(10456), 931", type: "Commentary", theme: "justice", c: 24, doi: "10.1016/S0140-6736(24)01713-6" },
    { y: 2024, t: "Discriminatory, racist and xenophobic policies and practice against child refugees, asylum seekers and undocumented migrants in European health systems", a: "AJ Stevens, Y Boukari, S English, A Kadir, BN Kumar, D Devakumar", v: "The Lancet Regional Health – Europe 41", type: "Article", theme: "justice", c: 57, doi: "10.1016/j.lanepe.2023.100834", featured: true },
    { y: 2024, t: "Gaza, armed conflict and child health", a: "Y Boukari, A Kadir, T Waterston, P Jarrett, C Harkensee, E Dexter, et al.", v: "BMJ Paediatrics Open 8(1), e002407", type: "Article", theme: "justice", c: 74, doi: "10.1136/bmjpo-2023-002407", featured: true },
    { y: 2024, t: "COVID-19 vaccination coverage for half a million non-EU migrants and refugees in England", a: "R Burns, S Wyke, MT Eyre, Y Boukari, TB Sørensen, C Tsang, et al.", v: "Nature Human Behaviour 8(2), 288–299", type: "Article", theme: "covid", c: 21, doi: "10.1038/s41562-023-01768-6", featured: true },
    { y: 2024, t: "Linking migration and hospital data in England: linkage process and evaluation of bias", a: "R Burns, S Wyke, Y Boukari, SV Katikireddi, D Zenner, I Campos-Matos, et al.", v: "International Journal of Population Data Science 9(1), 2181", type: "Article", theme: "data", c: 3, doi: "10.23889/ijpds.v9i1.2181" },
    { y: 2024, t: "The health dimensions of violence in Palestine: a call to prevent genocide", a: "A Faddoul, G Shannon, K Asghar, Y Boukari, J Smith, A Neilson", v: "The Lancet 403(10421), 25–26", type: "Commentary", theme: "justice", c: 27, doi: "10.1016/S0140-6736(23)02751-4" },
    { y: 2024, t: "Sexual and reproductive health and rights of migrant women attending primary care in England: a population-based cohort study of 1.2 million individuals of reproductive age", a: "N Pathak, CX Zhang, Y Boukari, R Burns, D Menezes, G Hugenholtz, et al.", v: "Journal of Migration and Health 9, 100214", type: "Article", theme: "data", c: 9, doi: "10.1016/j.jmh.2024.100214" },
    { y: 2024, t: "The incidence of COVID-19-related hospitalisation in migrants in the UK: findings from the Virus Watch prospective community cohort study", a: "WLE Fong, VG Nguyen, R Burns, Y Boukari, S Beale, I Braithwaite, et al.", v: "Journal of Migration and Health 9, 100218", type: "Article", theme: "covid", c: 7, doi: "10.1016/j.jmh.2024.100218" },
    { y: 2023, t: "Assessing the causal effect of air pollution on risk of SARS-CoV-2 infection", a: "AMD Navaratnam, S Beale, Y Boukari, V Nguyen, WLE Fong, et al.", v: "medRxiv", type: "Preprint", theme: "covid", c: 2, doi: "10.1101/2023.10.26.23297598" },
    { y: 2023, t: "SARS-CoV-2 infections in migrants and the role of household overcrowding: a causal mediation analysis of Virus Watch data", a: "Y Boukari, S Beale, V Nguyen, WLE Fong, R Burns, A Yavlinsky, et al.", v: "Journal of Epidemiology and Community Health 77(10), 649–655", type: "Article", theme: "covid", c: 8, doi: "10.1136/jech-2022-220251", featured: true },
    { y: 2023, t: "Deprivation, essential and non-essential activities and SARS-CoV-2 infection following the lifting of national public health restrictions in England and Wales", a: "S Hoskins, S Beale, V Nguyen, Y Boukari, A Yavlinsky, J Kovar, T Byrne, et al.", v: "NIHR Open Research 3, 46", type: "Article", theme: "covid", c: 2, doi: "10.3310/nihropenres.13445.1" },
    { y: 2023, t: "A case-crossover study of the effect of vaccination on SARS-CoV-2 transmission relevant behaviours during a period of national lockdown in England and Wales", a: "A Serisier, S Beale, Y Boukari, S Hoskins, V Nguyen, T Byrne, WLE Fong, et al.", v: "Vaccine 41(2), 511–518", type: "Article", theme: "covid", c: 11, doi: "10.1016/j.vaccine.2022.11.073" },
    { y: 2023, t: "Relative contribution of essential and non-essential activities to SARS-CoV-2 transmission following the lifting of public health restrictions in England and Wales", a: "S Hoskins, S Beale, V Nguyen, Y Boukari, A Yavlinsky, J Kovar, T Byrne, et al.", v: "Epidemiology & Infection 151, e3", type: "Article", theme: "covid", c: 12, doi: "10.1017/S0950268822001832" },
    { y: 2022, t: "Migrants' primary care utilisation before and during the COVID-19 pandemic in England: an interrupted time series analysis", a: "CX Zhang, Y Boukari, N Pathak, R Mathur, SV Katikireddi, P Patel, et al.", v: "The Lancet Regional Health – Europe 20", type: "Article", theme: "covid", c: 59, doi: "10.1016/j.lanepe.2022.100455" },
    { y: 2021, t: "Development and validation of a primary care electronic health record phenotype to study migration and health in the UK", a: "N Pathak, CX Zhang, Y Boukari, R Burns, R Mathur, A Gonzalez-Izquierdo, et al.", v: "Int. J. Environmental Research and Public Health 18(24), 13304", type: "Article", theme: "data", c: 20, doi: "10.3390/ijerph182413304" },
    { y: 2021, t: "Healthcare resource utilisation and mortality outcomes in international migrants to the UK: analysis protocol for a linked population-based cohort study using CPRD", a: "N Pathak, P Patel, R Burns, L Hiam, CX Zhang, Y Boukari, et al.", v: "Wellcome Open Research 5, 156", type: "Article", theme: "data", c: 7, doi: "10.12688/wellcomeopenres.15931.2" },
    { y: 2018, t: "Effect of volume of porogens on the porosity of PLGA scaffolds in pH-controlled environment", a: "M Gupta, A Aina, Y Boukari, S Doughty, A Morris, N Billa", v: "Pharmaceutical Development and Technology 23(2), 207–210", type: "Article", theme: "biomat", c: 9, doi: "10.1080/10837450.2017.1304415" },
    { y: 2017, t: "A dual-application poly(DL-lactic-co-glycolic) acid (PLGA)–chitosan composite scaffold for potential use in bone tissue engineering", a: "Y Boukari, O Qutachi, DJ Scurr, AP Morris, SW Doughty, N Billa", v: "Journal of Biomaterials Science, Polymer Edition 28(16), 1966–1983", type: "Article", theme: "biomat", c: 36, doi: "10.1080/09205063.2017.1364100" },
    { y: 2017, t: "A polymeric protein-loaded microsphere delivery system for use in bone tissue engineering", a: "Y Boukari", v: "PhD thesis, University of Nottingham", type: "Thesis", theme: "biomat", c: 0 },
    { y: 2016, t: "Monitoring model drug microencapsulation in PLGA scaffolds using X-ray powder diffraction", a: "A Aina, M Gupta, Y Boukari, A Morris, N Billa, S Doughty", v: "Saudi Pharmaceutical Journal 24(2), 227–231", type: "Article", theme: "biomat", c: 16, doi: "10.1016/j.jsps.2015.03.015" },
    { y: 2015, t: "Physicomechanical properties of sintered scaffolds formed from porous and protein-loaded poly(DL-lactic-co-glycolic acid) microspheres for potential use in bone tissue engineering", a: "Y Boukari, DJ Scurr, O Qutachi, AP Morris, SW Doughty, CV Rahman, et al.", v: "Journal of Biomaterials Science, Polymer Edition 26(12), 796–811", type: "Article", theme: "biomat", c: 15, doi: "10.1080/09205063.2015.1058696" },
    { y: 2014, t: "Dissolution behavior of poly vinyl alcohol in water and its effect on the physical morphologies of PLGA scaffolds", a: "A Aina, A Morris, M Gupta, N Billa, N Madhvani, R Sharma, S Doughty, et al.", v: "Pharmaceutical and Biosciences Journal", type: "Article", theme: "biomat", c: 25 }
  ]
};
